### ISSUE TITLE
Could you share your datasets with me？

### ISSUE THREAD

**Issue by imsjz** [alcasla/Automatic-Cold-Steel-Detection-Alarm#1]
Having read your paper about cold steel detection, I am interesting in this. I want to train the network for cold steel but i did't find the datasets in your repositories. So could you share your datasets of cold steel with me? Thank you .

**Comment by alcasla** [comment]
Hi. I am deploying a dedicated web linked to the repository. It will contain several mirror links to datasets from the paper where we study a knife detection system and a brightness preprocessing.
"Brightness guided preprocessing for automatic cold steel weapon detection in surveillance videos with deep learning" https://www.sciencedirect.com/science/article/pii/S0925231218313365

Meanwhile, this is the link to datasets in googledrive, for classification and detection. 
https://drive.google.com/drive/folders/1SWUzWRqC9apMI3ZUHIKgfXaUiyIj6HbG?usp=sharing

**Comment by imsjz** [comment]
Wow! Thank you so much! It helps me a lot! Best wishes!
